//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Plugins.WebMap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Plugins.WebMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Aerial Map.
        /// </summary>
        internal static string BingAerial {
            get {
                return ResourceManager.GetString("BingAerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Hybrid Map.
        /// </summary>
        internal static string BingHybrid {
            get {
                return ResourceManager.GetString("BingHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Street Map.
        /// </summary>
        internal static string BingRoads {
            get {
                return ResourceManager.GetString("BingRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascaded: .
        /// </summary>
        internal static string Cascaded {
            get {
                return ResourceManager.GetString("Cascaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esri Hydro Base Map.
        /// </summary>
        internal static string EsriHydroBaseMap {
            get {
                return ResourceManager.GetString("EsriHydroBaseMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esri World Imagery.
        /// </summary>
        internal static string EsriWorldImagery {
            get {
                return ResourceManager.GetString("EsriWorldImagery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esri World Street Map.
        /// </summary>
        internal static string EsriWorldStreetMap {
            get {
                return ResourceManager.GetString("EsriWorldStreetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esri World Topo.
        /// </summary>
        internal static string EsriWorldTopo {
            get {
                return ResourceManager.GetString("EsriWorldTopo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Height: .
        /// </summary>
        internal static string FixedHeight {
            get {
                return ResourceManager.GetString("FixedHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Width: .
        /// </summary>
        internal static string FixedWidth {
            get {
                return ResourceManager.GetString("FixedWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Map.
        /// </summary>
        internal static string GoogleMap {
            get {
                return ResourceManager.GetString("GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Terrain.
        /// </summary>
        internal static string GoogleTerrain {
            get {
                return ResourceManager.GetString("GoogleTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Basemap.
        /// </summary>
        internal static string Legend_Title {
            get {
                return ResourceManager.GetString("Legend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nodata {
            get {
                object obj = ResourceManager.GetObject("nodata", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSubsets: .
        /// </summary>
        internal static string NoSubsets {
            get {
                return ResourceManager.GetString("NoSubsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity: .
        /// </summary>
        internal static string Opacity_Box_Text {
            get {
                return ResourceManager.GetString("Opacity_Box_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change opacity of the basemap layer..
        /// </summary>
        internal static string Opacity_Box_ToolTip {
            get {
                return ResourceManager.GetString("Opacity_Box_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaque: .
        /// </summary>
        internal static string Opaque {
            get {
                return ResourceManager.GetString("Opaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Street Map.
        /// </summary>
        internal static string OpenStreetMap {
            get {
                return ResourceManager.GetString("OpenStreetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Basemap.
        /// </summary>
        internal static string Panel_Name {
            get {
                return ResourceManager.GetString("Panel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queryable: .
        /// </summary>
        internal static string Queryable {
            get {
                return ResourceManager.GetString("Queryable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CRS to view..
        /// </summary>
        internal static string SelectCrsToView {
            get {
                return ResourceManager.GetString("SelectCrsToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select layer to view..
        /// </summary>
        internal static string SelectLayerToView {
            get {
                return ResourceManager.GetString("SelectLayerToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select server to view..
        /// </summary>
        internal static string SelectServerToView {
            get {
                return ResourceManager.GetString("SelectServerToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change online basemap service..
        /// </summary>
        internal static string Service_Box_ToolTip {
            get {
                return ResourceManager.GetString("Service_Box_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read capabilities: {0}.
        /// </summary>
        internal static string UnableToReadCapabilities {
            get {
                return ResourceManager.GetString("UnableToReadCapabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported CRS. Select another CRS..
        /// </summary>
        internal static string UnsupportedCrs {
            get {
                return ResourceManager.GetString("UnsupportedCrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS.
        /// </summary>
        internal static string WMSMap {
            get {
                return ResourceManager.GetString("WMSMap", resourceCulture);
            }
        }
    }
}
