//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Symbology {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SymbologyMessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SymbologyMessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Symbology.SymbologyMessageStrings", typeof(SymbologyMessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Shaded Relief.
        /// </summary>
        internal static string DesktopRasterExt_CreatingShadedRelief {
            get {
                return ResourceManager.GetString("DesktopRasterExt_CreatingShadedRelief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting color scheme to bitmap..
        /// </summary>
        internal static string DesktopRasterExt_PaintingColorScheme {
            get {
                return ResourceManager.GetString("DesktopRasterExt_PaintingColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting Hillshade To Bitmap.
        /// </summary>
        internal static string DesktopRasterExt_PaintingHillshade {
            get {
                return ResourceManager.GetString("DesktopRasterExt_PaintingHillshade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closing bracket wasn&apos;t found..
        /// </summary>
        internal static string Expression_ClosingBracket {
            get {
                return ResourceManager.GetString("Expression_ClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is empty..
        /// </summary>
        internal static string Expression_Empty {
            get {
                return ResourceManager.GetString("Expression_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression contains empty fields..
        /// </summary>
        internal static string Expression_EmptyField {
            get {
                return ResourceManager.GetString("Expression_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following field wasn&apos;t found:.
        /// </summary>
        internal static string Expression_FieldNotFound {
            get {
                return ResourceManager.GetString("Expression_FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No left operand was found..
        /// </summary>
        internal static string Expression_LeftOperandMissing {
            get {
                return ResourceManager.GetString("Expression_LeftOperandMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not a number:.
        /// </summary>
        internal static string Expression_NotANumber {
            get {
                return ResourceManager.GetString("Expression_NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected operand. Found character {0} at position {1}..
        /// </summary>
        internal static string Expression_OperandExpected {
            get {
                return ResourceManager.GetString("Expression_OperandExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find operation..
        /// </summary>
        internal static string Expression_OperationNotFound {
            get {
                return ResourceManager.GetString("Expression_OperationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not supported..
        /// </summary>
        internal static string Expression_OperationNotSupported {
            get {
                return ResourceManager.GetString("Expression_OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected operator. Found character {0} at position {1}..
        /// </summary>
        internal static string Expression_OperatorExprected {
            get {
                return ResourceManager.GetString("Expression_OperatorExprected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an operator in place of a value..
        /// </summary>
        internal static string Expression_OpereratorInsteadOfValue {
            get {
                return ResourceManager.GetString("Expression_OpereratorInsteadOfValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + operation isn&apos;t allowed for boolean values..
        /// </summary>
        internal static string Expression_PlusNotAllowed {
            get {
                return ResourceManager.GetString("Expression_PlusNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No right operand was found..
        /// </summary>
        internal static string Expression_RightOperandMissing {
            get {
                return ResourceManager.GetString("Expression_RightOperandMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression contains unpaired square brackets..
        /// </summary>
        internal static string Expression_UnpairedBracket {
            get {
                return ResourceManager.GetString("Expression_UnpairedBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression contains unpaired text quotes..
        /// </summary>
        internal static string Expression_UnpairedTextquotes {
            get {
                return ResourceManager.GetString("Expression_UnpairedTextquotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division by zero..
        /// </summary>
        internal static string Expression_ZeroDivision {
            get {
                return ResourceManager.GetString("Expression_ZeroDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Layer from Selected Features.
        /// </summary>
        internal static string FeatureLayer_Create_Layer_From_Selected_Features {
            get {
                return ResourceManager.GetString("FeatureLayer_Create_Layer_From_Selected_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Excel file &apos;Data&apos; Label.
        /// </summary>
        internal static string FeatureLayer_Join_Excel_File {
            get {
                return ResourceManager.GetString("FeatureLayer_Join_Excel_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Setup.
        /// </summary>
        internal static string FeatureLayer_Label_Setup {
            get {
                return ResourceManager.GetString("FeatureLayer_Label_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeling.
        /// </summary>
        internal static string FeatureLayer_Labeling {
            get {
                return ResourceManager.GetString("FeatureLayer_Labeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string FeatureLayer_SelectAll {
            get {
                return ResourceManager.GetString("FeatureLayer_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select By Attributes.
        /// </summary>
        internal static string FeatureLayer_SelectByAttributes {
            get {
                return ResourceManager.GetString("FeatureLayer_SelectByAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string FeatureLayer_Selection {
            get {
                return ResourceManager.GetString("FeatureLayer_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        internal static string FeatureLayer_UnselectAll {
            get {
                return ResourceManager.GetString("FeatureLayer_UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Selected Features.
        /// </summary>
        internal static string FeatureLayer_Zoom_To_Selected {
            get {
                return ResourceManager.GetString("FeatureLayer_Zoom_To_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file %S can&apos;t be deleted, probably because it is currently in use by another application..
        /// </summary>
        internal static string FileCantBeDeletedException_S {
            get {
                return ResourceManager.GetString("FileCantBeDeletedException_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Layer_Properties {
            get {
                return ResourceManager.GetString("Layer_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        internal static string LayerFrame_CreateGroup {
            get {
                return ResourceManager.GetString("LayerFrame_CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Layers.
        /// </summary>
        internal static string LayerFrame_Map_Layers {
            get {
                return ResourceManager.GetString("LayerFrame_Map_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Map Frame.
        /// </summary>
        internal static string LayerFrame_RemoveMapFrame {
            get {
                return ResourceManager.GetString("LayerFrame_RemoveMapFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Map Frame.
        /// </summary>
        internal static string LayerFrame_ZoomToMapFrame {
            get {
                return ResourceManager.GetString("LayerFrame_ZoomToMapFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file type is not supported..
        /// </summary>
        internal static string LayerManager_FileTypeNotSupported {
            get {
                return ResourceManager.GetString("LayerManager_FileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incompatible feature type was supplied and was not of type Line..
        /// </summary>
        internal static string LineFeatureTypeException {
            get {
                return ResourceManager.GetString("LineFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument %S cannot be null..
        /// </summary>
        internal static string NullLogException_S {
            get {
                return ResourceManager.GetString("NullLogException_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incompatible feature type was supplied and was not of type Point..
        /// </summary>
        internal static string PointFeatureTypeException {
            get {
                return ResourceManager.GetString("PointFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incompatible feature type was supplied and was not of type polygon..
        /// </summary>
        internal static string PolygonFeatureTypeException {
            get {
                return ResourceManager.GetString("PolygonFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Layer.
        /// </summary>
        internal static string RemoveLayer {
            get {
                return ResourceManager.GetString("RemoveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Dynamic Visibility Scale.
        /// </summary>
        internal static string SetDynamicVisibilityScale {
            get {
                return ResourceManager.GetString("SetDynamicVisibilityScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Layer.
        /// </summary>
        internal static string ZoomToLayer {
            get {
                return ResourceManager.GetString("ZoomToLayer", resourceCulture);
            }
        }
    }
}
