// <autogenerated />
using System;
using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("DotSpatial.Data.Rasters.GdalExtension")]
[assembly: AssemblyDescription("Open rasters and other file formats using GDAL.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyProduct("DotSpatial.Data.Rasters.GdalExtension")]
[assembly: AssemblyCopyright("Copyright © DotSpatial Team 2012-2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("7e8e6d3c-7baa-40e0-8216-aa51fd2568e3")]