//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Plugins.SpatiaLite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Plugins.SpatiaLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the geometry_columns table..
        /// </summary>
        internal static string CouldNotFindTheGeometryColumnsTable {
            get {
                return ResourceManager.GetString("CouldNotFindTheGeometryColumnsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the SpatiaLite version..
        /// </summary>
        internal static string CouldNotFindTheSpatiaLiteVersion {
            get {
                return ResourceManager.GetString("CouldNotFindTheSpatiaLiteVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database: {0}.
        /// </summary>
        internal static string Database0 {
            get {
                return ResourceManager.GetString("Database0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database {0} is not a valid SpatiaLite database. {1}.
        /// </summary>
        internal static string DatabaseNotValid {
            get {
                return ResourceManager.GetString("DatabaseNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid query result found. Please re-run the query..
        /// </summary>
        internal static string NoValidQueryResultFound {
            get {
                return ResourceManager.GetString("NoValidQueryResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open SpatiaLite database.
        /// </summary>
        internal static string OpenSpatialiteDatabase {
            get {
                return ResourceManager.GetString("OpenSpatialiteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spatialite_open_16 {
            get {
                object obj = ResourceManager.GetObject("spatialite_open_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spatialite_open_32 {
            get {
                object obj = ResourceManager.GetObject("spatialite_open_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spatialite_query_16 {
            get {
                object obj = ResourceManager.GetObject("spatialite_query_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spatialite_query_32 {
            get {
                object obj = ResourceManager.GetObject("spatialite_query_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spatialite_save_16 {
            get {
                object obj = ResourceManager.GetObject("spatialite_save_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spatialite_save_32 {
            get {
                object obj = ResourceManager.GetObject("spatialite_save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpatiaLite database|*.sqlite.
        /// </summary>
        internal static string SpatialiteDatabaseFilter {
            get {
                return ResourceManager.GetString("SpatialiteDatabaseFilter", resourceCulture);
            }
        }
    }
}
