//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Symbology.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SymbologyFormsMessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SymbologyFormsMessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Symbology.Forms.SymbologyFormsMessageStrings", typeof(SymbologyFormsMessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorial value should be grater than 0.
        /// </summary>
        internal static string AttributeCalculator_FactGreaterThanZero {
            get {
                return ResourceManager.GetString("AttributeCalculator_FactGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination field data type is incompatible (double or string or integer).
        /// </summary>
        internal static string AttributeCalculator_IncompatibleDestinationField {
            get {
                return ResourceManager.GetString("AttributeCalculator_IncompatibleDestinationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function name was not recognized as one of the standard function names..
        /// </summary>
        internal static string AttributeCalculator_NonStandardFunction {
            get {
                return ResourceManager.GetString("AttributeCalculator_NonStandardFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is invalid.
        /// </summary>
        internal static string AttributeCalculator_ParameterInvalid {
            get {
                return ResourceManager.GetString("AttributeCalculator_ParameterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root n-th root is incorrect.
        /// </summary>
        internal static string AttributeCalculator_RootNthRootIncorrect {
            get {
                return ResourceManager.GetString("AttributeCalculator_RootNthRootIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were too many closing brackets in the string expression..
        /// </summary>
        internal static string AttributeCalculator_TooManyClosingBrackets {
            get {
                return ResourceManager.GetString("AttributeCalculator_TooManyClosingBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered could not be correctly parsed into a valid double precision floating point value..
        /// </summary>
        internal static string DoubleBox_DoubleError {
            get {
                return ResourceManager.GetString("DoubleBox_DoubleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a double precision floating point value..
        /// </summary>
        internal static string DoubleBox_DoubleHelp {
            get {
                return ResourceManager.GetString("DoubleBox_DoubleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Features.
        /// </summary>
        internal static string ExportFeature_FeaturesAll {
            get {
                return ResourceManager.GetString("ExportFeature_FeaturesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Features in View Extent.
        /// </summary>
        internal static string ExportFeature_FeaturesExtent {
            get {
                return ResourceManager.GetString("ExportFeature_FeaturesExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected features.
        /// </summary>
        internal static string ExportFeature_FeaturesSelected {
            get {
                return ResourceManager.GetString("ExportFeature_FeaturesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to specify a custom filter expression, the custom mode must be selected first..
        /// </summary>
        internal static string FeatureCategoryControl_CustomOnly {
            get {
                return ResourceManager.GetString("FeatureCategoryControl_CustomOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each symbol group can define a separate string expression that includes attribute values.  Double click fields to add it to the expression..
        /// </summary>
        internal static string LabelSetup_Help1 {
            get {
                return ResourceManager.GetString("LabelSetup_Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Members tab to design a filter expression that restricts which features will be assigned to a specific label..
        /// </summary>
        internal static string LabelSetup_Help2 {
            get {
                return ResourceManager.GetString("LabelSetup_Help2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Expression Tab to design the text that should appear in a label.  Fields indicated with brackets will be substituted with real values..
        /// </summary>
        internal static string LabelSetup_Help3 {
            get {
                return ResourceManager.GetString("LabelSetup_Help3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each group can specify its own basic design characteristics..
        /// </summary>
        internal static string LabelSetup_Help4 {
            get {
                return ResourceManager.GetString("LabelSetup_Help4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each group can specify its advanced characteristics..
        /// </summary>
        internal static string LabelSetup_Help5 {
            get {
                return ResourceManager.GetString("LabelSetup_Help5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet supported for tables with more than 50, 000 rows..
        /// </summary>
        internal static string LargeEditsNotSupported {
            get {
                return ResourceManager.GetString("LargeEditsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string TableEditorControl_Confirm {
            get {
                return ResourceManager.GetString("TableEditorControl_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy FID.
        /// </summary>
        internal static string TableEditorControl_CopyFid_Could_not_copy_FID {
            get {
                return ResourceManager.GetString("TableEditorControl_CopyFid_Could_not_copy_FID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the field in the attribute Table colums.
        /// </summary>
        internal static string TableEditorControl_CopyFid_Couldnt_find_field {
            get {
                return ResourceManager.GetString("TableEditorControl_CopyFid_Couldnt_find_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute the query..
        /// </summary>
        internal static string TableEditorControl_CouldNotExecuteQuery {
            get {
                return ResourceManager.GetString("TableEditorControl_CouldNotExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find or replace items..
        /// </summary>
        internal static string TableEditorControl_CouldNotFindReplace {
            get {
                return ResourceManager.GetString("TableEditorControl_CouldNotFindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string TableEditorControl_DisplaySelectedRowNumberLable__of_ {
            get {
                return ResourceManager.GetString("TableEditorControl_DisplaySelectedRowNumberLable__of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Selected.
        /// </summary>
        internal static string TableEditorControl_DisplaySelectedRowNumberLable__Selected {
            get {
                return ResourceManager.GetString("TableEditorControl_DisplaySelectedRowNumberLable__Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Find String.
        /// </summary>
        internal static string TableEditorControl_EnterFindString {
            get {
                return ResourceManager.GetString("TableEditorControl_EnterFindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapefiles (*.shp) |*.shp.
        /// </summary>
        internal static string TableEditorControl_exportSelectedFeaturesToolStripMenuItem_Click_Shapefiles____shp_____SHP {
            get {
                return ResourceManager.GetString("TableEditorControl_exportSelectedFeaturesToolStripMenuItem_Click_Shapefiles____sh" +
                        "p_____SHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import column fields..
        /// </summary>
        internal static string TableEditorControl_FieldImportFailed {
            get {
                return ResourceManager.GetString("TableEditorControl_FieldImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string TableEditorControl_Find {
            get {
                return ResourceManager.GetString("TableEditorControl_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import column fields.
        /// </summary>
        internal static string TableEditorControl_ImportFieldsFromDbf_Could_not_import_column_fields {
            get {
                return ResourceManager.GetString("TableEditorControl_ImportFieldsFromDbf_Could_not_import_column_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBase Files (*.dbf)|*.dbf.
        /// </summary>
        internal static string TableEditorControl_ImportFieldsFromDbf_DBase_Files____dbf____DBF {
            get {
                return ResourceManager.GetString("TableEditorControl_ImportFieldsFromDbf_DBase_Files____dbf____DBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create new field.
        /// </summary>
        internal static string TableEditorControl_NewFieldFail {
            get {
                return ResourceManager.GetString("TableEditorControl_NewFieldFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the rows contain a value that matches the specified value..
        /// </summary>
        internal static string TableEditorControl_NoMatch {
            get {
                return ResourceManager.GetString("TableEditorControl_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the fields?.
        /// </summary>
        internal static string TableEditorControl_RemoveFields {
            get {
                return ResourceManager.GetString("TableEditorControl_RemoveFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column edits are not yet supported for datasets with more than 50, 000 attributes.
        /// </summary>
        internal static string TableEditorControl_removeFieldToolStripMenuItem_Click_Column_edits_are_not_yet_supported_for_datasets_with_more_than_50_000_attributes {
            get {
                return ResourceManager.GetString("TableEditorControl_removeFieldToolStripMenuItem_Click_Column_edits_are_not_yet_su" +
                        "pported_for_datasets_with_more_than_50_000_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet supported for datasets with larger than 50, 000 rows..
        /// </summary>
        internal static string TableEditorControl_renameFieldToolStripMenuItem_Click_This_feature_is_not_yet_supported_for_datasets_with_larger_than_50_000_rows_ {
            get {
                return ResourceManager.GetString("TableEditorControl_renameFieldToolStripMenuItem_Click_This_feature_is_not_yet_sup" +
                        "ported_for_datasets_with_larger_than_50_000_rows_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfamilar data type to replace.
        /// </summary>
        internal static string TableEditorControl_ReplaceString_Unfamilar_data_type_to_replace {
            get {
                return ResourceManager.GetString("TableEditorControl_ReplaceString_Unfamilar_data_type_to_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row.
        /// </summary>
        internal static string TableEditorControl_Row {
            get {
                return ResourceManager.GetString("TableEditorControl_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rows.
        /// </summary>
        internal static string TableEditorControl_RowPlural {
            get {
                return ResourceManager.GetString("TableEditorControl_RowPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save edits. .
        /// </summary>
        internal static string TableEditorControl_SaveEdits_Unable_to_save_edits__ {
            get {
                return ResourceManager.GetString("TableEditorControl_SaveEdits_Unable_to_save_edits__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string TableEditorControl_SelectedRowCountPluralization {
            get {
                return ResourceManager.GetString("TableEditorControl_SelectedRowCountPluralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} selected..
        /// </summary>
        internal static string TableEditorControl_SelectedRowCountStringFormat {
            get {
                return ResourceManager.GetString("TableEditorControl_SelectedRowCountStringFormat", resourceCulture);
            }
        }
    }
}
