//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Symbology {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SymbologyMessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SymbologyMessageStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Symbology.SymbologyMessageStrings", typeof(SymbologyMessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creating Shaded Relief ähnelt.
        /// </summary>
        internal static string DesktopRasterExt_CreatingShadedRelief {
            get {
                return ResourceManager.GetString("DesktopRasterExt_CreatingShadedRelief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Painting color scheme to bitmap. ähnelt.
        /// </summary>
        internal static string DesktopRasterExt_PaintingColorScheme {
            get {
                return ResourceManager.GetString("DesktopRasterExt_PaintingColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Painting Hillshade To Bitmap ähnelt.
        /// </summary>
        internal static string DesktopRasterExt_PaintingHillshade {
            get {
                return ResourceManager.GetString("DesktopRasterExt_PaintingHillshade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Data ähnelt.
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The closing bracket wasn&apos;t found. ähnelt.
        /// </summary>
        internal static string Expression_ClosingBracket {
            get {
                return ResourceManager.GetString("Expression_ClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The expression is empty. ähnelt.
        /// </summary>
        internal static string Expression_Empty {
            get {
                return ResourceManager.GetString("Expression_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The expression contains empty fields. ähnelt.
        /// </summary>
        internal static string Expression_EmptyField {
            get {
                return ResourceManager.GetString("Expression_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following field wasn&apos;t found: ähnelt.
        /// </summary>
        internal static string Expression_FieldNotFound {
            get {
                return ResourceManager.GetString("Expression_FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No left operand was found. ähnelt.
        /// </summary>
        internal static string Expression_LeftOperandMissing {
            get {
                return ResourceManager.GetString("Expression_LeftOperandMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value is not a number: ähnelt.
        /// </summary>
        internal static string Expression_NotANumber {
            get {
                return ResourceManager.GetString("Expression_NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected operand. Found character {0} at position {1}. ähnelt.
        /// </summary>
        internal static string Expression_OperandExpected {
            get {
                return ResourceManager.GetString("Expression_OperandExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to find operation. ähnelt.
        /// </summary>
        internal static string Expression_OperationNotFound {
            get {
                return ResourceManager.GetString("Expression_OperationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation not supported. ähnelt.
        /// </summary>
        internal static string Expression_OperationNotSupported {
            get {
                return ResourceManager.GetString("Expression_OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected operator. Found character {0} at position {1}. ähnelt.
        /// </summary>
        internal static string Expression_OperatorExprected {
            get {
                return ResourceManager.GetString("Expression_OperatorExprected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is an operator in place of a value. ähnelt.
        /// </summary>
        internal static string Expression_OpereratorInsteadOfValue {
            get {
                return ResourceManager.GetString("Expression_OpereratorInsteadOfValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die + operation isn&apos;t allowed for boolean values. ähnelt.
        /// </summary>
        internal static string Expression_PlusNotAllowed {
            get {
                return ResourceManager.GetString("Expression_PlusNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No right operand was found. ähnelt.
        /// </summary>
        internal static string Expression_RightOperandMissing {
            get {
                return ResourceManager.GetString("Expression_RightOperandMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The expression contains unpaired square brackets. ähnelt.
        /// </summary>
        internal static string Expression_UnpairedBracket {
            get {
                return ResourceManager.GetString("Expression_UnpairedBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The expression contains unpaired text quotes. ähnelt.
        /// </summary>
        internal static string Expression_UnpairedTextquotes {
            get {
                return ResourceManager.GetString("Expression_UnpairedTextquotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Division by zero. ähnelt.
        /// </summary>
        internal static string Expression_ZeroDivision {
            get {
                return ResourceManager.GetString("Expression_ZeroDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Layer from Selected Features ähnelt.
        /// </summary>
        internal static string FeatureLayer_Create_Layer_From_Selected_Features {
            get {
                return ResourceManager.GetString("FeatureLayer_Create_Layer_From_Selected_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join Excel file &apos;Data&apos; Label ähnelt.
        /// </summary>
        internal static string FeatureLayer_Join_Excel_File {
            get {
                return ResourceManager.GetString("FeatureLayer_Join_Excel_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Label Setup ähnelt.
        /// </summary>
        internal static string FeatureLayer_Label_Setup {
            get {
                return ResourceManager.GetString("FeatureLayer_Label_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Labeling ähnelt.
        /// </summary>
        internal static string FeatureLayer_Labeling {
            get {
                return ResourceManager.GetString("FeatureLayer_Labeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All ähnelt.
        /// </summary>
        internal static string FeatureLayer_SelectAll {
            get {
                return ResourceManager.GetString("FeatureLayer_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection ähnelt.
        /// </summary>
        internal static string FeatureLayer_Selection {
            get {
                return ResourceManager.GetString("FeatureLayer_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unselect All ähnelt.
        /// </summary>
        internal static string FeatureLayer_UnselectAll {
            get {
                return ResourceManager.GetString("FeatureLayer_UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom to Selected Features ähnelt.
        /// </summary>
        internal static string FeatureLayer_Zoom_To_Selected {
            get {
                return ResourceManager.GetString("FeatureLayer_Zoom_To_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file %S can&apos;t be deleted, probably because it is currently in use by another application. ähnelt.
        /// </summary>
        internal static string FileCantBeDeletedException_S {
            get {
                return ResourceManager.GetString("FileCantBeDeletedException_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        internal static string Layer_Properties {
            get {
                return ResourceManager.GetString("Layer_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Group ähnelt.
        /// </summary>
        internal static string LayerFrame_CreateGroup {
            get {
                return ResourceManager.GetString("LayerFrame_CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Map Layers ähnelt.
        /// </summary>
        internal static string LayerFrame_Map_Layers {
            get {
                return ResourceManager.GetString("LayerFrame_Map_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Map Frame ähnelt.
        /// </summary>
        internal static string LayerFrame_RemoveMapFrame {
            get {
                return ResourceManager.GetString("LayerFrame_RemoveMapFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom to Map Frame ähnelt.
        /// </summary>
        internal static string LayerFrame_ZoomToMapFrame {
            get {
                return ResourceManager.GetString("LayerFrame_ZoomToMapFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified file type is not supported. ähnelt.
        /// </summary>
        internal static string LayerManager_FileTypeNotSupported {
            get {
                return ResourceManager.GetString("LayerManager_FileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An incompatible feature type was supplied and was not of type Line. ähnelt.
        /// </summary>
        internal static string LineFeatureTypeException {
            get {
                return ResourceManager.GetString("LineFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The argument %S cannot be null. ähnelt.
        /// </summary>
        internal static string NullLogException_S {
            get {
                return ResourceManager.GetString("NullLogException_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An incompatible feature type was supplied and was not of type Point. ähnelt.
        /// </summary>
        internal static string PointFeatureTypeException {
            get {
                return ResourceManager.GetString("PointFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An incompatible feature type was supplied and was not of type polygon. ähnelt.
        /// </summary>
        internal static string PolygonFeatureTypeException {
            get {
                return ResourceManager.GetString("PolygonFeatureTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Layer ähnelt.
        /// </summary>
        internal static string RemoveLayer {
            get {
                return ResourceManager.GetString("RemoveLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Dynamic Visibility Scale ähnelt.
        /// </summary>
        internal static string SetDynamicVisibilityScale {
            get {
                return ResourceManager.GetString("SetDynamicVisibilityScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom to Layer ähnelt.
        /// </summary>
        internal static string ZoomToLayer {
            get {
                return ResourceManager.GetString("ZoomToLayer", resourceCulture);
            }
        }
    }
}
