//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Plugins.ShapeEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShapeEditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShapeEditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Plugins.ShapeEditor.ShapeEditorResources", typeof(ShapeEditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Add_Ctx_DeleteShape {
            get {
                return ResourceManager.GetString("Add_Ctx_DeleteShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Part.
        /// </summary>
        internal static string Add_Ctx_FinishPart {
            get {
                return ResourceManager.GetString("Add_Ctx_FinishPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Shape.
        /// </summary>
        internal static string Add_Ctx_FinishShape {
            get {
                return ResourceManager.GetString("Add_Ctx_FinishShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shape.
        /// </summary>
        internal static string Add_Shape {
            get {
                return ResourceManager.GetString("Add_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap move {
            get {
                object obj = ResourceManager.GetObject("move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue from Endpoint.
        /// </summary>
        internal static string Move_Ctx_ContinueEnd {
            get {
                return ResourceManager.GetString("Move_Ctx_ContinueEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue from Start point.
        /// </summary>
        internal static string Move_Ctx_ContinueStart {
            get {
                return ResourceManager.GetString("Move_Ctx_ContinueStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete vertex.
        /// </summary>
        internal static string Move_Ctx_DeteleVertex {
            get {
                return ResourceManager.GetString("Move_Ctx_DeteleVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert vertex.
        /// </summary>
        internal static string Move_Ctx_InsertVertex {
            get {
                return ResourceManager.GetString("Move_Ctx_InsertVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Vertex.
        /// </summary>
        internal static string Move_Vertex {
            get {
                return ResourceManager.GetString("Move_Vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NewShape {
            get {
                object obj = ResourceManager.GetObject("NewShape", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NewShapefile {
            get {
                object obj = ResourceManager.GetObject("NewShapefile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape dragging Active.
        /// </summary>
        internal static string ShapeDragging_Active {
            get {
                return ResourceManager.GetString("ShapeDragging_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape dragging Inactive.
        /// </summary>
        internal static string ShapeDragging_InActive {
            get {
                return ResourceManager.GetString("ShapeDragging_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices index on selected feature are showned.
        /// </summary>
        internal static string ShowVerticesIndex_Active {
            get {
                return ResourceManager.GetString("ShowVerticesIndex_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices index on selected feature are hided.
        /// </summary>
        internal static string ShowVerticesIndex_InActive {
            get {
                return ResourceManager.GetString("ShowVerticesIndex_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices.
        /// </summary>
        internal static string ShowVerticesIndex_Label {
            get {
                return ResourceManager.GetString("ShowVerticesIndex_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Snapping Active.
        /// </summary>
        internal static string Snapping_Active {
            get {
                return ResourceManager.GetString("Snapping_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Snapping Inactive.
        /// </summary>
        internal static string Snapping_InActive {
            get {
                return ResourceManager.GetString("Snapping_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapping.
        /// </summary>
        internal static string Snapping_Label {
            get {
                return ResourceManager.GetString("Snapping_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapping Settings.
        /// </summary>
        internal static string Snapping_Settings {
            get {
                return ResourceManager.GetString("Snapping_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SnappingIcon {
            get {
                object obj = ResourceManager.GetObject("SnappingIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
