//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Projections {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Projections.ProjectionMessages", typeof(ProjectionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name %S was found for more than one lla Table in the Nad folder..
        /// </summary>
        internal static string DuplicateTableName {
            get {
                return ResourceManager.GetString("DuplicateTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arguments in initialization list.
        /// </summary>
        internal static string Err1_NoArguments {
            get {
                return ResourceManager.GetString("Err1_NoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reciprocal flattening (1/f) = 0.
        /// </summary>
        internal static string Err10_ZeroRecFlattening {
            get {
                return ResourceManager.GetString("Err10_ZeroRecFlattening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Latitude was greater than 90 or less than -90.
        /// </summary>
        internal static string Err11_LatitudeOutOfBounds {
            get {
                return ResourceManager.GetString("Err11_LatitudeOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The square of eccentricity cannot be a negative value..
        /// </summary>
        internal static string Err12_ESquareNegative {
            get {
                return ResourceManager.GetString("Err12_ESquareNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given semi-major axis was 0 or not given..
        /// </summary>
        internal static string Err13_NoMajorRadius {
            get {
                return ResourceManager.GetString("Err13_NoMajorRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Latitude or Longitude exceeded limits.
        /// </summary>
        internal static string Err14_LatLonOutOfBounds {
            get {
                return ResourceManager.GetString("Err14_LatLonOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cartesian X or Y coordinate was invalid.
        /// </summary>
        internal static string Err15_InvalidXY {
            get {
                return ResourceManager.GetString("Err15_InvalidXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Degree Minute Second value is formed imporperly.
        /// </summary>
        internal static string Err16_ImproperDMS {
            get {
                return ResourceManager.GetString("Err16_ImproperDMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inverse meridinal distance was non-convergent.
        /// </summary>
        internal static string Err17_NonConvergentRMeridDist {
            get {
                return ResourceManager.GetString("Err17_NonConvergentRMeridDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inverse Phi2 value was non-converngent.
        /// </summary>
        internal static string Err18_NonConvergentRPhi2 {
            get {
                return ResourceManager.GetString("Err18_NonConvergentRPhi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ArcCosign or ArcSign value was too large..
        /// </summary>
        internal static string Err19_TrigException {
            get {
                return ResourceManager.GetString("Err19_TrigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options found in &apos;init&apos; file.
        /// </summary>
        internal static string Err2_NoOptions {
            get {
                return ResourceManager.GetString("Err2_NoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance Condition Error.
        /// </summary>
        internal static string Err20_ToleranceConditionError {
            get {
                return ResourceManager.GetString("Err20_ToleranceConditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conic lat_1 value cannot be its -lat_2.
        /// </summary>
        internal static string Err21_ConicLatitudeError {
            get {
                return ResourceManager.GetString("Err21_ConicLatitudeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude 1 cannot be greater than or equal to 90.
        /// </summary>
        internal static string Err22_Lat1TooLarge {
            get {
                return ResourceManager.GetString("Err22_Lat1TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude 2 cannot be equal to 0.
        /// </summary>
        internal static string Err23_Lat1TooSmall {
            get {
                return ResourceManager.GetString("Err23_Lat1TooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lat_ts parameter cannot be greater than or equal to 90.
        /// </summary>
        internal static string Err24_Lat_tsTooLarge {
            get {
                return ResourceManager.GetString("Err24_Lat_tsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no distance between the control points.
        /// </summary>
        internal static string Err25_NoControlPtSeparation {
            get {
                return ResourceManager.GetString("Err25_NoControlPtSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection not selected to be rotated.
        /// </summary>
        internal static string Err26_ProjectionNotRotated {
            get {
                return ResourceManager.GetString("Err26_ProjectionNotRotated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W &lt;= 0 or M &lt;= 0.
        /// </summary>
        internal static string Err27_WorMTooSmall {
            get {
                return ResourceManager.GetString("Err27_WorMTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lsat not in 1-5 range.
        /// </summary>
        internal static string Err28_LsatOutOfBounds {
            get {
                return ResourceManager.GetString("Err28_LsatOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not in range.
        /// </summary>
        internal static string Err29_PathNotInRange {
            get {
                return ResourceManager.GetString("Err29_PathNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No colon in init= string.
        /// </summary>
        internal static string Err3_NoColon {
            get {
                return ResourceManager.GetString("Err3_NoColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H was negative or 0.
        /// </summary>
        internal static string Err30_HTooSmall {
            get {
                return ResourceManager.GetString("Err30_HTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K was less than 0.
        /// </summary>
        internal static string Err31_KTooSmall {
            get {
                return ResourceManager.GetString("Err31_KTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The central latitude was 0 or 90 or alpha = 90.
        /// </summary>
        internal static string Err32_LatOutOfBounds {
            get {
                return ResourceManager.GetString("Err32_LatOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat_1 = lat_2 or lat_1 = 0 or lat_2 = 90.
        /// </summary>
        internal static string Err33_InvalidLatitudes {
            get {
                return ResourceManager.GetString("Err33_InvalidLatitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elliptical Usage Required.
        /// </summary>
        internal static string Err34_EllipticalRequired {
            get {
                return ResourceManager.GetString("Err34_EllipticalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UTM zone parameter was invalid.
        /// </summary>
        internal static string Err35_InvalidUTMZone {
            get {
                return ResourceManager.GetString("Err35_InvalidUTMZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments were out of range for Tcheby eval.
        /// </summary>
        internal static string Err36_TchebyException {
            get {
                return ResourceManager.GetString("Err36_TchebyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection Not Found.
        /// </summary>
        internal static string Err37_ProjNotFound {
            get {
                return ResourceManager.GetString("Err37_ProjNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load NAD27-83 correction file.
        /// </summary>
        internal static string Err38_CorrectionNotFound {
            get {
                return ResourceManager.GetString("Err38_CorrectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both n and m must be specified and &gt; 0.
        /// </summary>
        internal static string Err39_NorMnotSpecified {
            get {
                return ResourceManager.GetString("Err39_NorMnotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection not named.
        /// </summary>
        internal static string Err4_NotNamed {
            get {
                return ResourceManager.GetString("Err4_NotNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&lt;= 0, n &gt; 1 or not specified.
        /// </summary>
        internal static string Err40_InvalidN {
            get {
                return ResourceManager.GetString("Err40_InvalidN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lat_1 or lat_2 not specified.
        /// </summary>
        internal static string Err41_Lat1OrLat2Missing {
            get {
                return ResourceManager.GetString("Err41_Lat1OrLat2Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |lat_1| =|lat_2| .
        /// </summary>
        internal static string Err42_Lat1EqualsLat2 {
            get {
                return ResourceManager.GetString("Err42_Lat1EqualsLat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lat_0 is pi/2 from mean lat.
        /// </summary>
        internal static string Err43_MeanLatError {
            get {
                return ResourceManager.GetString("Err43_MeanLatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse coordinate system definition.
        /// </summary>
        internal static string Err44_CoordinateUnreadable {
            get {
                return ResourceManager.GetString("Err44_CoordinateUnreadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocentric transformation missing z or ellips.
        /// </summary>
        internal static string Err45_GeocentricMissingZ {
            get {
                return ResourceManager.GetString("Err45_GeocentricMissingZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uknown prime meridian conversion ID.
        /// </summary>
        internal static string Err46_UknownPMID {
            get {
                return ResourceManager.GetString("Err46_UknownPMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnknownProjectionId.
        /// </summary>
        internal static string Err5_UknownProjection {
            get {
                return ResourceManager.GetString("Err5_UknownProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective eccentricity = 1.
        /// </summary>
        internal static string Err6_EffectiveEccentricity1 {
            get {
                return ResourceManager.GetString("Err6_EffectiveEccentricity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown unit conversion ID.
        /// </summary>
        internal static string Err7_UknownUnitID {
            get {
                return ResourceManager.GetString("Err7_UknownUnitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid boolean parameter argument.
        /// </summary>
        internal static string Err8_Invalidboolean {
            get {
                return ResourceManager.GetString("Err8_Invalidboolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elliptical parameter ellps= was unkown.
        /// </summary>
        internal static string Err9_UknownEllipse {
            get {
                return ResourceManager.GetString("Err9_UknownEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an index mismatch problem with the specified file..
        /// </summary>
        internal static string IndexMismatch {
            get {
                return ResourceManager.GetString("IndexMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse grid shift iteration faield, presumably at grid edge.  Using first approximation..
        /// </summary>
        internal static string InverseShiftFailed {
            get {
                return ResourceManager.GetString("InverseShiftFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse grid shift iterator failed to converge..
        /// </summary>
        internal static string InvShiftConvergeFailed {
            get {
                return ResourceManager.GetString("InvShiftConvergeFailed", resourceCulture);
            }
        }
    }
}
