//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Plugins.WebMap.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Services : global::System.Configuration.ApplicationSettingsBase {
        
        private static Services defaultInstance = ((Services)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Services())));
        
        public static Services Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Bing Street Map,http://tiles.virtualearth.net/tiles/r{key}.png?g=461&amp;mkt=en-us,19</string>
  <string>Bing Aerial Map,http://tiles.virtualearth.net/tiles/h{key}.jpeg?g=461&amp;mkt=en-us&amp;n=z,19</string>
  <string>ESRI Hydro Base Map,http://bmproto.esri.com/ArcGIS/rest/services/Hydro/HydroBase2009/MapServer/tile/{zoom}/{y}/{x},11</string>
  <string>ESRI World Street Map,http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{zoom}/{y}/{x},17</string>
  <string>ESRI World Imagery,http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{zoom}/{y}/{x},15</string>
  <string>ESRI World Topo,http://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{zoom}/{y}/{x},19</string>
  <string>OpenStreetMap,http://tile.openstreetmap.org/{zoom}/{x}/{y}.png,18</string>
  <string>ESRI World Hydro Overlay,http://184.72.212.114:6080/arcgis/rest/services/WorldHydroReferenceOverlay/MapServer/tile/{zoom}/{y}/{x}</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection List {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["List"]));
            }
            set {
                this["List"] = value;
            }
        }
    }
}
