// <autogenerated />
using System;
using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("DotSpatial.Symbology.Forms")]
[assembly: AssemblyDescription("Windows forms controls related to customizing map cartographic symbols.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyProduct("DotSpatial.Symbology.Forms")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: CLSCompliant(true)]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components. If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("d73f1a25-3f64-4174-a480-93926db72fbf")]