//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace DotSpatial.Data.Forms {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class DataFormsMessageStrings {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataFormsMessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("DotSpatial.Data.Forms.DataFormsMessageStrings", typeof(DataFormsMessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current element was not defined.  Before attempting to read the element, first assign the value of the current XML Element to read..
        /// </summary>
        internal static string CurrentElementNotSpecified {
            get {
                return ResourceManager.GetString("CurrentElementNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value..
        /// </summary>
        internal static string ExtentDialog_Fail_Invalid_Value {
            get {
                return ResourceManager.GetString("ExtentDialog_Fail_Invalid_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to box.  Either fix the value to represent a double precision floating point value or choose cancel..
        /// </summary>
        internal static string ExtentDialog_Fail_Post {
            get {
                return ResourceManager.GetString("ExtentDialog_Fail_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an invalid entry in the.
        /// </summary>
        internal static string ExtentDialog_Fail_Pre {
            get {
                return ResourceManager.GetString("ExtentDialog_Fail_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value you entered could not be parsed into a %S.  Make sure the value is in the valid range..
        /// </summary>
        internal static string ParseFailed_S {
            get {
                return ResourceManager.GetString("ParseFailed_S", resourceCulture);
            }
        }
    }
}
