// <autogenerated />
using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("DotSpatial.Tools")]
[assembly: AssemblyDescription("A set of tools used for geoprocessing operations.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyProduct("DotSpatial.Tools")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("85e44f63-1c01-4972-a665-06f7640bd0d3")]