// <autogenerated />
using System;
using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("DotSpatial.Extensions")]
[assembly: AssemblyDescription("Interfaces which allow DotSpatial to be extended.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyProduct("DotSpatial.Extensions")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: CLSCompliant(true)]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("3d68cb2b-b75a-47ec-90b9-2bf009510bf2")]