// <autogenerated />
using System.Reflection;

[assembly: AssemblyCompany("DotSpatial Team")]
[assembly: AssemblyVersion("3.0")]
[assembly: AssemblyFileVersion("3.0")]
[assembly: AssemblyCopyright("Copyright © DotSpatial Team 2012-2022")]