//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Data.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataFormsMessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataFormsMessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Data.Forms.DataFormsMessageStrings", typeof(DataFormsMessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current element was not defined.  Before attempting to read the element, first assign the value of the current XML Element to read..
        /// </summary>
        internal static string CurrentElementNotSpecified {
            get {
                return ResourceManager.GetString("CurrentElementNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value..
        /// </summary>
        internal static string ExtentDialog_Fail_Invalid_Value {
            get {
                return ResourceManager.GetString("ExtentDialog_Fail_Invalid_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to box.  Either fix the value to represent a double precision floating point value or choose cancel..
        /// </summary>
        internal static string ExtentDialog_Fail_Post {
            get {
                return ResourceManager.GetString("ExtentDialog_Fail_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an invalid entry in the.
        /// </summary>
        internal static string ExtentDialog_Fail_Pre {
            get {
                return ResourceManager.GetString("ExtentDialog_Fail_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value you entered could not be parsed into a %S.  Make sure the value is in the valid range..
        /// </summary>
        internal static string ParseFailed_S {
            get {
                return ResourceManager.GetString("ParseFailed_S", resourceCulture);
            }
        }
    }
}
